name: Firebase Production Deploy

on:
  push:
    branches: [main]
    paths:
      - 'client/**'

jobs:
  firebase-stage-deploy:
    name: Firebase Development Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup Node v16
        uses: actions/setup-node@master
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: cd client && yarn install --frozen-lockfile

      - name: Build React WebApp
        run: cd client && yarn build:dev

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: plugapp-78c2a
          channelId: live